name: CMake Linux

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  linux-build-gcc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install tools
        run: sudo apt-get install -y gcc cmake make

      - name: Configure CMake
        run: cmake $GITHUB_WORKSPACE -B bin -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=gcc -DLYRA_BUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build bin --parallel
  
  linux-build-clang:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install tools
        run: sudo apt-get install -y clang cmake make

      - name: Configure CMake
        run: cmake $GITHUB_WORKSPACE -B bin -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=clang -DLYRA_BUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build bin --parallel
  
  linux-build-tcc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install tools
        run: sudo apt-get install -y tcc cmake make

      - name: Configure CMake
        run: cmake $GITHUB_WORKSPACE -B bin -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=tcc -DLYRA_BUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build bin --parallel
