name: Linux Tests

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  tests-gcc:
    needs: linux-build-gcc
    runs-on: ubuntu-latest

    steps:
      - name: Download Tests
        uses: actions/download-artifact@v3
        with:
          name: tests_gcc

      - name: Run Tests
        shell: bash
        run: chmod +x tests_gcc && ./tests_gcc
